---
- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted

- name: Enable unbound
  ansible.builtin.systemd:
    name: unbound
    enabled: true

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
